### ISSUE TITLE
Search errors when trying to reach bookwyrm.social

### ISSUE THREAD

**Issue by renatolond** [mouse-reeve/bookwyrm#428]
**Describe the bug**
I've create an instance to test bookwyrm.social. When I try to import my goodreads csv, I get several "Error loading book." errors. When looking it up closely, it seems the fails comes from when it tries to use the bookwyrm.social connector. It seems there's an internal error, but still it answers with 200.
It's possible to reproduce the error from a local test instance by searching for a book such as "Unquenchable Fire"

**To Reproduce**
1. Go to bookwyrm
2. Search for "Unquenchable Fire"
3. See error

**Expected behavior**
The search works correctly

**Backtrace**
```
Environment:


Request Method: GET
Request URL: http://localhost:1333/search/?q=Unquenchable+Fire

Django Version: 3.0.7
Python Version: 3.8.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django_rename_app',
 'bookwyrm',
 'celery']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

During handling of the above exception (1), another exception occurred:
  File "/home/renatocerqueira/src/bookwyrm/.virtualenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/renatocerqueira/src/bookwyrm/.virtualenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/renatocerqueira/src/bookwyrm/.virtualenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/renatocerqueira/src/bookwyrm/.virtualenv/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/renatocerqueira/src/bookwyrm/bookwyrm/views.py", line 226, in search
    book_results = books_manager.search(query)
  File "/home/renatocerqueira/src/bookwyrm/bookwyrm/books_manager.py", line 57, in search
    result_set = connector.search(query, min_confidence=min_confidence)
  File "/home/renatocerqueira/src/bookwyrm/bookwyrm/connectors/abstract_connector.py", line 49, in search
    data = resp.json()
  File "/home/renatocerqueira/src/bookwyrm/.virtualenv/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

Exception Type: JSONDecodeError at /search/
Exception Value: Expecting value: line 2 column 1 (char 1)
```

**Additional context**
I think one of the problems is that one failing connector seems to make the whole search fail. The second issue is that bookwyrm.social is answering with html to a request with `accept: application/json; charset=utf-8`

**Comment by mouse-reeve** [comment]
thank you for flagging this! yeah, I agree this seems like a convergence of a) bookwyrm.social having a server error for some reason, b) the local instance failing when one connector fails, and c) bookwyrm responding with the http 200 html error page as if it was a json response, instead of serving an error code
