### ISSUE TITLE
Database errors after updating

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#777]
**Describe the bug**
Running `docker-compose up --build` after updating the production branch with `git pull` brought many database errors.

**To Reproduce**
I don't know if it's universal but I went back to a snapshot after I faced the issues.

**Logs**
Very repetitive and only a cut-out since my terminal only keeps so many lines and I had reset the machine to keep it running, sorry for not having the full logs.
[db_1 errors](https://gist.github.com/tofuwabohu/2ead9655b9eb20f2efc7551125df19cf)
[web_1 errors](https://gist.github.com/tofuwabohu/ee98ad484eb732da932890d4e75e3844) (shown after the db_1 errors)

**Additional context**
I jumped from commit #fd4b2adb8b31065eede754159118634411c1d93d to #bb8cac021b6bc41a99cc317a87c1c39ef8a5987e

**Comment by mouse-reeve** [comment]
I _think_ all you need to do to fix this is run the migrations (unless you have already, in which case hmmmm). I use `./bw-dev update` when I update my instance, which git pulls, runs migrations, runs collectstatic, and restarts the images

**Comment by tofuwabohu** [comment]
Ah, I should have another look at that tool, thanks!

Running `./bw-dev update` didn't work out unfortunately:

``` python
[...]
 34 files changed, 661 insertions(+), 48 deletions(-)
 create mode 100644 bookwyrm/migrations/0056_auto_20210321_0303.py
 create mode 100644 bookwyrm/templates/email/html_layout.html
 create mode 100644 bookwyrm/templates/email/invite/html_content.html
 create mode 100644 bookwyrm/templates/email/invite/subject.html
 create mode 100644 bookwyrm/templates/email/invite/text_content.html
 create mode 100644 bookwyrm/templates/email/password_reset/html_content.html
 create mode 100644 bookwyrm/templates/email/password_reset/subject.html
 create mode 100644 bookwyrm/templates/email/password_reset/text_content.html
 create mode 100644 bookwyrm/templates/email/preview.html
 create mode 100644 bookwyrm/templates/email/snippets/action.html
 create mode 100644 bookwyrm/templates/email/text_layout.html
 create mode 100644 bookwyrm/templates/settings/manage_invite_requests.html
 create mode 100644 bookwyrm/tests/test_emailing.py
+ docker-compose exec web python manage.py migrate
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/bookwyrm/models/__init__.py", line 27, in <module>
    from .import_job import ImportJob, ImportItem
  File "/app/bookwyrm/models/import_job.py", line 67, in <module>
    class ImportItem(models.Model):
  File "/app/bookwyrm/models/import_job.py", line 72, in ImportItem
    data = models.JSONField()
AttributeError: module 'django.db.models' has no attribute 'JSONField'

```

**Comment by mouse-reeve** [comment]
Ah, you need to upgrade the django version with pip -- running `docker-compose up --build`  should do it, and if not, `docker-compose run web pip install -r requirements.txt`  and `docker-compose run celery_worker pip install -r requirements.txt` 

I'll update the command to handle that

**Comment by tofuwabohu** [comment]
This worked, thank you!
